services:
  team-performance-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: team-performance-app
    restart: unless-stopped
    env_file:
      - .env.production
    ports:
      - "3000:3000"